package com.ritchey.simple.mapper.chapel;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.ritchey.simple.domain.chapel.ChapelPerson;
import com.ritchey.simple.domain.chapel.ChapelPersonExample;

public interface ChapelPersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    int countByExample(ChapelPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    int deleteByExample(ChapelPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    int insert(ChapelPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    int insertSelective(ChapelPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    List<ChapelPerson> selectByExample(ChapelPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    ChapelPerson selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    int updateByExampleSelective(@Param("record") ChapelPerson record, @Param("example") ChapelPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    int updateByExample(@Param("record") ChapelPerson record, @Param("example") ChapelPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    int updateByPrimaryKeySelective(ChapelPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    int updateByPrimaryKey(ChapelPerson record);
}