package com.ritchey.simple.mapper.chapel;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.ritchey.simple.domain.chapel.Exemptions;
import com.ritchey.simple.domain.chapel.ExemptionsExample;

public interface ExemptionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exemptions
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    int countByExample(ExemptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exemptions
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    int deleteByExample(ExemptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exemptions
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exemptions
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    int insert(Exemptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exemptions
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    int insertSelective(Exemptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exemptions
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    List<Exemptions> selectByExampleWithBLOBs(ExemptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exemptions
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    List<Exemptions> selectByExample(ExemptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exemptions
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    Exemptions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exemptions
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    int updateByExampleSelective(@Param("record") Exemptions record, @Param("example") ExemptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exemptions
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    int updateByExampleWithBLOBs(@Param("record") Exemptions record, @Param("example") ExemptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exemptions
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    int updateByExample(@Param("record") Exemptions record, @Param("example") ExemptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exemptions
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    int updateByPrimaryKeySelective(Exemptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exemptions
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    int updateByPrimaryKeyWithBLOBs(Exemptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exemptions
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    int updateByPrimaryKey(Exemptions record);
    
    Map getExemptions(@Param("peopleId") String peopleId, @Param("endterm") Date endTerm);
}