package com.ritchey.simple.mapper.chapel;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.ritchey.simple.domain.chapel.Punch;
import com.ritchey.simple.domain.chapel.PunchExample;

public interface PunchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punch
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    int countByExample(PunchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punch
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    int deleteByExample(PunchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punch
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punch
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    int insert(Punch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punch
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    int insertSelective(Punch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punch
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    List<Punch> selectByExampleWithBLOBs(PunchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punch
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    List<Punch> selectByExample(PunchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punch
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    Punch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punch
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    int updateByExampleSelective(@Param("record") Punch record, @Param("example") PunchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punch
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    int updateByExampleWithBLOBs(@Param("record") Punch record, @Param("example") PunchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punch
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    int updateByExample(@Param("record") Punch record, @Param("example") PunchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punch
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    int updateByPrimaryKeySelective(Punch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punch
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    int updateByPrimaryKeyWithBLOBs(Punch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punch
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    int updateByPrimaryKey(Punch record);
    
    List<Map> selectPresent(@Param("campusId") String campusId, @Param("startterm") Date startterm, RowBounds r);
    List<Map> selectPresent(@Param("campusId") String campusId, @Param("startterm") Date startterm);
    Map selectPresentCount(@Param("campusId") String campusId, @Param("startterm") Date startterm);
    List<Map> selectTardy(@Param("campusId") String campusId, @Param("startterm") Date startterm, RowBounds r);
    List<Map> selectTardy(@Param("campusId") String campusId, @Param("startterm") Date startterm);
    Map selectTardyCount(@Param("campusId") String campusId, @Param("startterm") Date startterm);
    
}