package com.ritchey.simple.domain.powercampus;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AcademicCalendarExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public AcademicCalendarExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getName());
        sb.append("[");
        sb.append("Hash = ").append(hashCode());
        sb.append(",orderByClause=").append(orderByClause);
        sb.append(",distinct=").append(distinct);
        sb.append(",oredCriteria=").append(oredCriteria);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAcademicYearIsNull() {
            addCriterion("ACADEMIC_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andAcademicYearIsNotNull() {
            addCriterion("ACADEMIC_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andAcademicYearEqualTo(String value) {
            addCriterion("ACADEMIC_YEAR =", value, "academicYear");
            return (Criteria) this;
        }

        public Criteria andAcademicYearNotEqualTo(String value) {
            addCriterion("ACADEMIC_YEAR <>", value, "academicYear");
            return (Criteria) this;
        }

        public Criteria andAcademicYearGreaterThan(String value) {
            addCriterion("ACADEMIC_YEAR >", value, "academicYear");
            return (Criteria) this;
        }

        public Criteria andAcademicYearGreaterThanOrEqualTo(String value) {
            addCriterion("ACADEMIC_YEAR >=", value, "academicYear");
            return (Criteria) this;
        }

        public Criteria andAcademicYearLessThan(String value) {
            addCriterion("ACADEMIC_YEAR <", value, "academicYear");
            return (Criteria) this;
        }

        public Criteria andAcademicYearLessThanOrEqualTo(String value) {
            addCriterion("ACADEMIC_YEAR <=", value, "academicYear");
            return (Criteria) this;
        }

        public Criteria andAcademicYearLike(String value) {
            addCriterion("ACADEMIC_YEAR like", value, "academicYear");
            return (Criteria) this;
        }

        public Criteria andAcademicYearNotLike(String value) {
            addCriterion("ACADEMIC_YEAR not like", value, "academicYear");
            return (Criteria) this;
        }

        public Criteria andAcademicYearIn(List<String> values) {
            addCriterion("ACADEMIC_YEAR in", values, "academicYear");
            return (Criteria) this;
        }

        public Criteria andAcademicYearNotIn(List<String> values) {
            addCriterion("ACADEMIC_YEAR not in", values, "academicYear");
            return (Criteria) this;
        }

        public Criteria andAcademicYearBetween(String value1, String value2) {
            addCriterion("ACADEMIC_YEAR between", value1, value2, "academicYear");
            return (Criteria) this;
        }

        public Criteria andAcademicYearNotBetween(String value1, String value2) {
            addCriterion("ACADEMIC_YEAR not between", value1, value2, "academicYear");
            return (Criteria) this;
        }

        public Criteria andAcademicTermIsNull() {
            addCriterion("ACADEMIC_TERM is null");
            return (Criteria) this;
        }

        public Criteria andAcademicTermIsNotNull() {
            addCriterion("ACADEMIC_TERM is not null");
            return (Criteria) this;
        }

        public Criteria andAcademicTermEqualTo(String value) {
            addCriterion("ACADEMIC_TERM =", value, "academicTerm");
            return (Criteria) this;
        }

        public Criteria andAcademicTermNotEqualTo(String value) {
            addCriterion("ACADEMIC_TERM <>", value, "academicTerm");
            return (Criteria) this;
        }

        public Criteria andAcademicTermGreaterThan(String value) {
            addCriterion("ACADEMIC_TERM >", value, "academicTerm");
            return (Criteria) this;
        }

        public Criteria andAcademicTermGreaterThanOrEqualTo(String value) {
            addCriterion("ACADEMIC_TERM >=", value, "academicTerm");
            return (Criteria) this;
        }

        public Criteria andAcademicTermLessThan(String value) {
            addCriterion("ACADEMIC_TERM <", value, "academicTerm");
            return (Criteria) this;
        }

        public Criteria andAcademicTermLessThanOrEqualTo(String value) {
            addCriterion("ACADEMIC_TERM <=", value, "academicTerm");
            return (Criteria) this;
        }

        public Criteria andAcademicTermLike(String value) {
            addCriterion("ACADEMIC_TERM like", value, "academicTerm");
            return (Criteria) this;
        }

        public Criteria andAcademicTermNotLike(String value) {
            addCriterion("ACADEMIC_TERM not like", value, "academicTerm");
            return (Criteria) this;
        }

        public Criteria andAcademicTermIn(List<String> values) {
            addCriterion("ACADEMIC_TERM in", values, "academicTerm");
            return (Criteria) this;
        }

        public Criteria andAcademicTermNotIn(List<String> values) {
            addCriterion("ACADEMIC_TERM not in", values, "academicTerm");
            return (Criteria) this;
        }

        public Criteria andAcademicTermBetween(String value1, String value2) {
            addCriterion("ACADEMIC_TERM between", value1, value2, "academicTerm");
            return (Criteria) this;
        }

        public Criteria andAcademicTermNotBetween(String value1, String value2) {
            addCriterion("ACADEMIC_TERM not between", value1, value2, "academicTerm");
            return (Criteria) this;
        }

        public Criteria andAcademicSessionIsNull() {
            addCriterion("ACADEMIC_SESSION is null");
            return (Criteria) this;
        }

        public Criteria andAcademicSessionIsNotNull() {
            addCriterion("ACADEMIC_SESSION is not null");
            return (Criteria) this;
        }

        public Criteria andAcademicSessionEqualTo(String value) {
            addCriterion("ACADEMIC_SESSION =", value, "academicSession");
            return (Criteria) this;
        }

        public Criteria andAcademicSessionNotEqualTo(String value) {
            addCriterion("ACADEMIC_SESSION <>", value, "academicSession");
            return (Criteria) this;
        }

        public Criteria andAcademicSessionGreaterThan(String value) {
            addCriterion("ACADEMIC_SESSION >", value, "academicSession");
            return (Criteria) this;
        }

        public Criteria andAcademicSessionGreaterThanOrEqualTo(String value) {
            addCriterion("ACADEMIC_SESSION >=", value, "academicSession");
            return (Criteria) this;
        }

        public Criteria andAcademicSessionLessThan(String value) {
            addCriterion("ACADEMIC_SESSION <", value, "academicSession");
            return (Criteria) this;
        }

        public Criteria andAcademicSessionLessThanOrEqualTo(String value) {
            addCriterion("ACADEMIC_SESSION <=", value, "academicSession");
            return (Criteria) this;
        }

        public Criteria andAcademicSessionLike(String value) {
            addCriterion("ACADEMIC_SESSION like", value, "academicSession");
            return (Criteria) this;
        }

        public Criteria andAcademicSessionNotLike(String value) {
            addCriterion("ACADEMIC_SESSION not like", value, "academicSession");
            return (Criteria) this;
        }

        public Criteria andAcademicSessionIn(List<String> values) {
            addCriterion("ACADEMIC_SESSION in", values, "academicSession");
            return (Criteria) this;
        }

        public Criteria andAcademicSessionNotIn(List<String> values) {
            addCriterion("ACADEMIC_SESSION not in", values, "academicSession");
            return (Criteria) this;
        }

        public Criteria andAcademicSessionBetween(String value1, String value2) {
            addCriterion("ACADEMIC_SESSION between", value1, value2, "academicSession");
            return (Criteria) this;
        }

        public Criteria andAcademicSessionNotBetween(String value1, String value2) {
            addCriterion("ACADEMIC_SESSION not between", value1, value2, "academicSession");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("START_DATE is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("START_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(Date value) {
            addCriterion("START_DATE =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(Date value) {
            addCriterion("START_DATE <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(Date value) {
            addCriterion("START_DATE >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(Date value) {
            addCriterion("START_DATE >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(Date value) {
            addCriterion("START_DATE <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(Date value) {
            addCriterion("START_DATE <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<Date> values) {
            addCriterion("START_DATE in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<Date> values) {
            addCriterion("START_DATE not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(Date value1, Date value2) {
            addCriterion("START_DATE between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(Date value1, Date value2) {
            addCriterion("START_DATE not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("END_DATE is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("END_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(Date value) {
            addCriterion("END_DATE =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(Date value) {
            addCriterion("END_DATE <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(Date value) {
            addCriterion("END_DATE >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
            addCriterion("END_DATE >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(Date value) {
            addCriterion("END_DATE <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(Date value) {
            addCriterion("END_DATE <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<Date> values) {
            addCriterion("END_DATE in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<Date> values) {
            addCriterion("END_DATE not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(Date value1, Date value2) {
            addCriterion("END_DATE between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(Date value1, Date value2) {
            addCriterion("END_DATE not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andFiscalYearIsNull() {
            addCriterion("FISCAL_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andFiscalYearIsNotNull() {
            addCriterion("FISCAL_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andFiscalYearEqualTo(String value) {
            addCriterion("FISCAL_YEAR =", value, "fiscalYear");
            return (Criteria) this;
        }

        public Criteria andFiscalYearNotEqualTo(String value) {
            addCriterion("FISCAL_YEAR <>", value, "fiscalYear");
            return (Criteria) this;
        }

        public Criteria andFiscalYearGreaterThan(String value) {
            addCriterion("FISCAL_YEAR >", value, "fiscalYear");
            return (Criteria) this;
        }

        public Criteria andFiscalYearGreaterThanOrEqualTo(String value) {
            addCriterion("FISCAL_YEAR >=", value, "fiscalYear");
            return (Criteria) this;
        }

        public Criteria andFiscalYearLessThan(String value) {
            addCriterion("FISCAL_YEAR <", value, "fiscalYear");
            return (Criteria) this;
        }

        public Criteria andFiscalYearLessThanOrEqualTo(String value) {
            addCriterion("FISCAL_YEAR <=", value, "fiscalYear");
            return (Criteria) this;
        }

        public Criteria andFiscalYearLike(String value) {
            addCriterion("FISCAL_YEAR like", value, "fiscalYear");
            return (Criteria) this;
        }

        public Criteria andFiscalYearNotLike(String value) {
            addCriterion("FISCAL_YEAR not like", value, "fiscalYear");
            return (Criteria) this;
        }

        public Criteria andFiscalYearIn(List<String> values) {
            addCriterion("FISCAL_YEAR in", values, "fiscalYear");
            return (Criteria) this;
        }

        public Criteria andFiscalYearNotIn(List<String> values) {
            addCriterion("FISCAL_YEAR not in", values, "fiscalYear");
            return (Criteria) this;
        }

        public Criteria andFiscalYearBetween(String value1, String value2) {
            addCriterion("FISCAL_YEAR between", value1, value2, "fiscalYear");
            return (Criteria) this;
        }

        public Criteria andFiscalYearNotBetween(String value1, String value2) {
            addCriterion("FISCAL_YEAR not between", value1, value2, "fiscalYear");
            return (Criteria) this;
        }

        public Criteria andAcademicWeeksIsNull() {
            addCriterion("ACADEMIC_WEEKS is null");
            return (Criteria) this;
        }

        public Criteria andAcademicWeeksIsNotNull() {
            addCriterion("ACADEMIC_WEEKS is not null");
            return (Criteria) this;
        }

        public Criteria andAcademicWeeksEqualTo(Integer value) {
            addCriterion("ACADEMIC_WEEKS =", value, "academicWeeks");
            return (Criteria) this;
        }

        public Criteria andAcademicWeeksNotEqualTo(Integer value) {
            addCriterion("ACADEMIC_WEEKS <>", value, "academicWeeks");
            return (Criteria) this;
        }

        public Criteria andAcademicWeeksGreaterThan(Integer value) {
            addCriterion("ACADEMIC_WEEKS >", value, "academicWeeks");
            return (Criteria) this;
        }

        public Criteria andAcademicWeeksGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACADEMIC_WEEKS >=", value, "academicWeeks");
            return (Criteria) this;
        }

        public Criteria andAcademicWeeksLessThan(Integer value) {
            addCriterion("ACADEMIC_WEEKS <", value, "academicWeeks");
            return (Criteria) this;
        }

        public Criteria andAcademicWeeksLessThanOrEqualTo(Integer value) {
            addCriterion("ACADEMIC_WEEKS <=", value, "academicWeeks");
            return (Criteria) this;
        }

        public Criteria andAcademicWeeksIn(List<Integer> values) {
            addCriterion("ACADEMIC_WEEKS in", values, "academicWeeks");
            return (Criteria) this;
        }

        public Criteria andAcademicWeeksNotIn(List<Integer> values) {
            addCriterion("ACADEMIC_WEEKS not in", values, "academicWeeks");
            return (Criteria) this;
        }

        public Criteria andAcademicWeeksBetween(Integer value1, Integer value2) {
            addCriterion("ACADEMIC_WEEKS between", value1, value2, "academicWeeks");
            return (Criteria) this;
        }

        public Criteria andAcademicWeeksNotBetween(Integer value1, Integer value2) {
            addCriterion("ACADEMIC_WEEKS not between", value1, value2, "academicWeeks");
            return (Criteria) this;
        }

        public Criteria andAcademicMonthsIsNull() {
            addCriterion("ACADEMIC_MONTHS is null");
            return (Criteria) this;
        }

        public Criteria andAcademicMonthsIsNotNull() {
            addCriterion("ACADEMIC_MONTHS is not null");
            return (Criteria) this;
        }

        public Criteria andAcademicMonthsEqualTo(Integer value) {
            addCriterion("ACADEMIC_MONTHS =", value, "academicMonths");
            return (Criteria) this;
        }

        public Criteria andAcademicMonthsNotEqualTo(Integer value) {
            addCriterion("ACADEMIC_MONTHS <>", value, "academicMonths");
            return (Criteria) this;
        }

        public Criteria andAcademicMonthsGreaterThan(Integer value) {
            addCriterion("ACADEMIC_MONTHS >", value, "academicMonths");
            return (Criteria) this;
        }

        public Criteria andAcademicMonthsGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACADEMIC_MONTHS >=", value, "academicMonths");
            return (Criteria) this;
        }

        public Criteria andAcademicMonthsLessThan(Integer value) {
            addCriterion("ACADEMIC_MONTHS <", value, "academicMonths");
            return (Criteria) this;
        }

        public Criteria andAcademicMonthsLessThanOrEqualTo(Integer value) {
            addCriterion("ACADEMIC_MONTHS <=", value, "academicMonths");
            return (Criteria) this;
        }

        public Criteria andAcademicMonthsIn(List<Integer> values) {
            addCriterion("ACADEMIC_MONTHS in", values, "academicMonths");
            return (Criteria) this;
        }

        public Criteria andAcademicMonthsNotIn(List<Integer> values) {
            addCriterion("ACADEMIC_MONTHS not in", values, "academicMonths");
            return (Criteria) this;
        }

        public Criteria andAcademicMonthsBetween(Integer value1, Integer value2) {
            addCriterion("ACADEMIC_MONTHS between", value1, value2, "academicMonths");
            return (Criteria) this;
        }

        public Criteria andAcademicMonthsNotBetween(Integer value1, Integer value2) {
            addCriterion("ACADEMIC_MONTHS not between", value1, value2, "academicMonths");
            return (Criteria) this;
        }

        public Criteria andNumberCoursesIsNull() {
            addCriterion("NUMBER_COURSES is null");
            return (Criteria) this;
        }

        public Criteria andNumberCoursesIsNotNull() {
            addCriterion("NUMBER_COURSES is not null");
            return (Criteria) this;
        }

        public Criteria andNumberCoursesEqualTo(Integer value) {
            addCriterion("NUMBER_COURSES =", value, "numberCourses");
            return (Criteria) this;
        }

        public Criteria andNumberCoursesNotEqualTo(Integer value) {
            addCriterion("NUMBER_COURSES <>", value, "numberCourses");
            return (Criteria) this;
        }

        public Criteria andNumberCoursesGreaterThan(Integer value) {
            addCriterion("NUMBER_COURSES >", value, "numberCourses");
            return (Criteria) this;
        }

        public Criteria andNumberCoursesGreaterThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_COURSES >=", value, "numberCourses");
            return (Criteria) this;
        }

        public Criteria andNumberCoursesLessThan(Integer value) {
            addCriterion("NUMBER_COURSES <", value, "numberCourses");
            return (Criteria) this;
        }

        public Criteria andNumberCoursesLessThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_COURSES <=", value, "numberCourses");
            return (Criteria) this;
        }

        public Criteria andNumberCoursesIn(List<Integer> values) {
            addCriterion("NUMBER_COURSES in", values, "numberCourses");
            return (Criteria) this;
        }

        public Criteria andNumberCoursesNotIn(List<Integer> values) {
            addCriterion("NUMBER_COURSES not in", values, "numberCourses");
            return (Criteria) this;
        }

        public Criteria andNumberCoursesBetween(Integer value1, Integer value2) {
            addCriterion("NUMBER_COURSES between", value1, value2, "numberCourses");
            return (Criteria) this;
        }

        public Criteria andNumberCoursesNotBetween(Integer value1, Integer value2) {
            addCriterion("NUMBER_COURSES not between", value1, value2, "numberCourses");
            return (Criteria) this;
        }

        public Criteria andPreRegDateIsNull() {
            addCriterion("PRE_REG_DATE is null");
            return (Criteria) this;
        }

        public Criteria andPreRegDateIsNotNull() {
            addCriterion("PRE_REG_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andPreRegDateEqualTo(Date value) {
            addCriterion("PRE_REG_DATE =", value, "preRegDate");
            return (Criteria) this;
        }

        public Criteria andPreRegDateNotEqualTo(Date value) {
            addCriterion("PRE_REG_DATE <>", value, "preRegDate");
            return (Criteria) this;
        }

        public Criteria andPreRegDateGreaterThan(Date value) {
            addCriterion("PRE_REG_DATE >", value, "preRegDate");
            return (Criteria) this;
        }

        public Criteria andPreRegDateGreaterThanOrEqualTo(Date value) {
            addCriterion("PRE_REG_DATE >=", value, "preRegDate");
            return (Criteria) this;
        }

        public Criteria andPreRegDateLessThan(Date value) {
            addCriterion("PRE_REG_DATE <", value, "preRegDate");
            return (Criteria) this;
        }

        public Criteria andPreRegDateLessThanOrEqualTo(Date value) {
            addCriterion("PRE_REG_DATE <=", value, "preRegDate");
            return (Criteria) this;
        }

        public Criteria andPreRegDateIn(List<Date> values) {
            addCriterion("PRE_REG_DATE in", values, "preRegDate");
            return (Criteria) this;
        }

        public Criteria andPreRegDateNotIn(List<Date> values) {
            addCriterion("PRE_REG_DATE not in", values, "preRegDate");
            return (Criteria) this;
        }

        public Criteria andPreRegDateBetween(Date value1, Date value2) {
            addCriterion("PRE_REG_DATE between", value1, value2, "preRegDate");
            return (Criteria) this;
        }

        public Criteria andPreRegDateNotBetween(Date value1, Date value2) {
            addCriterion("PRE_REG_DATE not between", value1, value2, "preRegDate");
            return (Criteria) this;
        }

        public Criteria andRegDateIsNull() {
            addCriterion("REG_DATE is null");
            return (Criteria) this;
        }

        public Criteria andRegDateIsNotNull() {
            addCriterion("REG_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andRegDateEqualTo(Date value) {
            addCriterion("REG_DATE =", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateNotEqualTo(Date value) {
            addCriterion("REG_DATE <>", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateGreaterThan(Date value) {
            addCriterion("REG_DATE >", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateGreaterThanOrEqualTo(Date value) {
            addCriterion("REG_DATE >=", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateLessThan(Date value) {
            addCriterion("REG_DATE <", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateLessThanOrEqualTo(Date value) {
            addCriterion("REG_DATE <=", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateIn(List<Date> values) {
            addCriterion("REG_DATE in", values, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateNotIn(List<Date> values) {
            addCriterion("REG_DATE not in", values, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateBetween(Date value1, Date value2) {
            addCriterion("REG_DATE between", value1, value2, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateNotBetween(Date value1, Date value2) {
            addCriterion("REG_DATE not between", value1, value2, "regDate");
            return (Criteria) this;
        }

        public Criteria andLastRegDateIsNull() {
            addCriterion("LAST_REG_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastRegDateIsNotNull() {
            addCriterion("LAST_REG_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastRegDateEqualTo(Date value) {
            addCriterion("LAST_REG_DATE =", value, "lastRegDate");
            return (Criteria) this;
        }

        public Criteria andLastRegDateNotEqualTo(Date value) {
            addCriterion("LAST_REG_DATE <>", value, "lastRegDate");
            return (Criteria) this;
        }

        public Criteria andLastRegDateGreaterThan(Date value) {
            addCriterion("LAST_REG_DATE >", value, "lastRegDate");
            return (Criteria) this;
        }

        public Criteria andLastRegDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_REG_DATE >=", value, "lastRegDate");
            return (Criteria) this;
        }

        public Criteria andLastRegDateLessThan(Date value) {
            addCriterion("LAST_REG_DATE <", value, "lastRegDate");
            return (Criteria) this;
        }

        public Criteria andLastRegDateLessThanOrEqualTo(Date value) {
            addCriterion("LAST_REG_DATE <=", value, "lastRegDate");
            return (Criteria) this;
        }

        public Criteria andLastRegDateIn(List<Date> values) {
            addCriterion("LAST_REG_DATE in", values, "lastRegDate");
            return (Criteria) this;
        }

        public Criteria andLastRegDateNotIn(List<Date> values) {
            addCriterion("LAST_REG_DATE not in", values, "lastRegDate");
            return (Criteria) this;
        }

        public Criteria andLastRegDateBetween(Date value1, Date value2) {
            addCriterion("LAST_REG_DATE between", value1, value2, "lastRegDate");
            return (Criteria) this;
        }

        public Criteria andLastRegDateNotBetween(Date value1, Date value2) {
            addCriterion("LAST_REG_DATE not between", value1, value2, "lastRegDate");
            return (Criteria) this;
        }

        public Criteria andGradeWthdrwlDateIsNull() {
            addCriterion("GRADE_WTHDRWL_DATE is null");
            return (Criteria) this;
        }

        public Criteria andGradeWthdrwlDateIsNotNull() {
            addCriterion("GRADE_WTHDRWL_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andGradeWthdrwlDateEqualTo(Date value) {
            addCriterion("GRADE_WTHDRWL_DATE =", value, "gradeWthdrwlDate");
            return (Criteria) this;
        }

        public Criteria andGradeWthdrwlDateNotEqualTo(Date value) {
            addCriterion("GRADE_WTHDRWL_DATE <>", value, "gradeWthdrwlDate");
            return (Criteria) this;
        }

        public Criteria andGradeWthdrwlDateGreaterThan(Date value) {
            addCriterion("GRADE_WTHDRWL_DATE >", value, "gradeWthdrwlDate");
            return (Criteria) this;
        }

        public Criteria andGradeWthdrwlDateGreaterThanOrEqualTo(Date value) {
            addCriterion("GRADE_WTHDRWL_DATE >=", value, "gradeWthdrwlDate");
            return (Criteria) this;
        }

        public Criteria andGradeWthdrwlDateLessThan(Date value) {
            addCriterion("GRADE_WTHDRWL_DATE <", value, "gradeWthdrwlDate");
            return (Criteria) this;
        }

        public Criteria andGradeWthdrwlDateLessThanOrEqualTo(Date value) {
            addCriterion("GRADE_WTHDRWL_DATE <=", value, "gradeWthdrwlDate");
            return (Criteria) this;
        }

        public Criteria andGradeWthdrwlDateIn(List<Date> values) {
            addCriterion("GRADE_WTHDRWL_DATE in", values, "gradeWthdrwlDate");
            return (Criteria) this;
        }

        public Criteria andGradeWthdrwlDateNotIn(List<Date> values) {
            addCriterion("GRADE_WTHDRWL_DATE not in", values, "gradeWthdrwlDate");
            return (Criteria) this;
        }

        public Criteria andGradeWthdrwlDateBetween(Date value1, Date value2) {
            addCriterion("GRADE_WTHDRWL_DATE between", value1, value2, "gradeWthdrwlDate");
            return (Criteria) this;
        }

        public Criteria andGradeWthdrwlDateNotBetween(Date value1, Date value2) {
            addCriterion("GRADE_WTHDRWL_DATE not between", value1, value2, "gradeWthdrwlDate");
            return (Criteria) this;
        }

        public Criteria andGradePenaltyDateIsNull() {
            addCriterion("GRADE_PENALTY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andGradePenaltyDateIsNotNull() {
            addCriterion("GRADE_PENALTY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andGradePenaltyDateEqualTo(Date value) {
            addCriterion("GRADE_PENALTY_DATE =", value, "gradePenaltyDate");
            return (Criteria) this;
        }

        public Criteria andGradePenaltyDateNotEqualTo(Date value) {
            addCriterion("GRADE_PENALTY_DATE <>", value, "gradePenaltyDate");
            return (Criteria) this;
        }

        public Criteria andGradePenaltyDateGreaterThan(Date value) {
            addCriterion("GRADE_PENALTY_DATE >", value, "gradePenaltyDate");
            return (Criteria) this;
        }

        public Criteria andGradePenaltyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("GRADE_PENALTY_DATE >=", value, "gradePenaltyDate");
            return (Criteria) this;
        }

        public Criteria andGradePenaltyDateLessThan(Date value) {
            addCriterion("GRADE_PENALTY_DATE <", value, "gradePenaltyDate");
            return (Criteria) this;
        }

        public Criteria andGradePenaltyDateLessThanOrEqualTo(Date value) {
            addCriterion("GRADE_PENALTY_DATE <=", value, "gradePenaltyDate");
            return (Criteria) this;
        }

        public Criteria andGradePenaltyDateIn(List<Date> values) {
            addCriterion("GRADE_PENALTY_DATE in", values, "gradePenaltyDate");
            return (Criteria) this;
        }

        public Criteria andGradePenaltyDateNotIn(List<Date> values) {
            addCriterion("GRADE_PENALTY_DATE not in", values, "gradePenaltyDate");
            return (Criteria) this;
        }

        public Criteria andGradePenaltyDateBetween(Date value1, Date value2) {
            addCriterion("GRADE_PENALTY_DATE between", value1, value2, "gradePenaltyDate");
            return (Criteria) this;
        }

        public Criteria andGradePenaltyDateNotBetween(Date value1, Date value2) {
            addCriterion("GRADE_PENALTY_DATE not between", value1, value2, "gradePenaltyDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateOpidIsNull() {
            addCriterion("CREATE_OPID is null");
            return (Criteria) this;
        }

        public Criteria andCreateOpidIsNotNull() {
            addCriterion("CREATE_OPID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateOpidEqualTo(String value) {
            addCriterion("CREATE_OPID =", value, "createOpid");
            return (Criteria) this;
        }

        public Criteria andCreateOpidNotEqualTo(String value) {
            addCriterion("CREATE_OPID <>", value, "createOpid");
            return (Criteria) this;
        }

        public Criteria andCreateOpidGreaterThan(String value) {
            addCriterion("CREATE_OPID >", value, "createOpid");
            return (Criteria) this;
        }

        public Criteria andCreateOpidGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_OPID >=", value, "createOpid");
            return (Criteria) this;
        }

        public Criteria andCreateOpidLessThan(String value) {
            addCriterion("CREATE_OPID <", value, "createOpid");
            return (Criteria) this;
        }

        public Criteria andCreateOpidLessThanOrEqualTo(String value) {
            addCriterion("CREATE_OPID <=", value, "createOpid");
            return (Criteria) this;
        }

        public Criteria andCreateOpidLike(String value) {
            addCriterion("CREATE_OPID like", value, "createOpid");
            return (Criteria) this;
        }

        public Criteria andCreateOpidNotLike(String value) {
            addCriterion("CREATE_OPID not like", value, "createOpid");
            return (Criteria) this;
        }

        public Criteria andCreateOpidIn(List<String> values) {
            addCriterion("CREATE_OPID in", values, "createOpid");
            return (Criteria) this;
        }

        public Criteria andCreateOpidNotIn(List<String> values) {
            addCriterion("CREATE_OPID not in", values, "createOpid");
            return (Criteria) this;
        }

        public Criteria andCreateOpidBetween(String value1, String value2) {
            addCriterion("CREATE_OPID between", value1, value2, "createOpid");
            return (Criteria) this;
        }

        public Criteria andCreateOpidNotBetween(String value1, String value2) {
            addCriterion("CREATE_OPID not between", value1, value2, "createOpid");
            return (Criteria) this;
        }

        public Criteria andCreateTerminalIsNull() {
            addCriterion("CREATE_TERMINAL is null");
            return (Criteria) this;
        }

        public Criteria andCreateTerminalIsNotNull() {
            addCriterion("CREATE_TERMINAL is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTerminalEqualTo(String value) {
            addCriterion("CREATE_TERMINAL =", value, "createTerminal");
            return (Criteria) this;
        }

        public Criteria andCreateTerminalNotEqualTo(String value) {
            addCriterion("CREATE_TERMINAL <>", value, "createTerminal");
            return (Criteria) this;
        }

        public Criteria andCreateTerminalGreaterThan(String value) {
            addCriterion("CREATE_TERMINAL >", value, "createTerminal");
            return (Criteria) this;
        }

        public Criteria andCreateTerminalGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TERMINAL >=", value, "createTerminal");
            return (Criteria) this;
        }

        public Criteria andCreateTerminalLessThan(String value) {
            addCriterion("CREATE_TERMINAL <", value, "createTerminal");
            return (Criteria) this;
        }

        public Criteria andCreateTerminalLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TERMINAL <=", value, "createTerminal");
            return (Criteria) this;
        }

        public Criteria andCreateTerminalLike(String value) {
            addCriterion("CREATE_TERMINAL like", value, "createTerminal");
            return (Criteria) this;
        }

        public Criteria andCreateTerminalNotLike(String value) {
            addCriterion("CREATE_TERMINAL not like", value, "createTerminal");
            return (Criteria) this;
        }

        public Criteria andCreateTerminalIn(List<String> values) {
            addCriterion("CREATE_TERMINAL in", values, "createTerminal");
            return (Criteria) this;
        }

        public Criteria andCreateTerminalNotIn(List<String> values) {
            addCriterion("CREATE_TERMINAL not in", values, "createTerminal");
            return (Criteria) this;
        }

        public Criteria andCreateTerminalBetween(String value1, String value2) {
            addCriterion("CREATE_TERMINAL between", value1, value2, "createTerminal");
            return (Criteria) this;
        }

        public Criteria andCreateTerminalNotBetween(String value1, String value2) {
            addCriterion("CREATE_TERMINAL not between", value1, value2, "createTerminal");
            return (Criteria) this;
        }

        public Criteria andRevisionDateIsNull() {
            addCriterion("REVISION_DATE is null");
            return (Criteria) this;
        }

        public Criteria andRevisionDateIsNotNull() {
            addCriterion("REVISION_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andRevisionDateEqualTo(Date value) {
            addCriterion("REVISION_DATE =", value, "revisionDate");
            return (Criteria) this;
        }

        public Criteria andRevisionDateNotEqualTo(Date value) {
            addCriterion("REVISION_DATE <>", value, "revisionDate");
            return (Criteria) this;
        }

        public Criteria andRevisionDateGreaterThan(Date value) {
            addCriterion("REVISION_DATE >", value, "revisionDate");
            return (Criteria) this;
        }

        public Criteria andRevisionDateGreaterThanOrEqualTo(Date value) {
            addCriterion("REVISION_DATE >=", value, "revisionDate");
            return (Criteria) this;
        }

        public Criteria andRevisionDateLessThan(Date value) {
            addCriterion("REVISION_DATE <", value, "revisionDate");
            return (Criteria) this;
        }

        public Criteria andRevisionDateLessThanOrEqualTo(Date value) {
            addCriterion("REVISION_DATE <=", value, "revisionDate");
            return (Criteria) this;
        }

        public Criteria andRevisionDateIn(List<Date> values) {
            addCriterion("REVISION_DATE in", values, "revisionDate");
            return (Criteria) this;
        }

        public Criteria andRevisionDateNotIn(List<Date> values) {
            addCriterion("REVISION_DATE not in", values, "revisionDate");
            return (Criteria) this;
        }

        public Criteria andRevisionDateBetween(Date value1, Date value2) {
            addCriterion("REVISION_DATE between", value1, value2, "revisionDate");
            return (Criteria) this;
        }

        public Criteria andRevisionDateNotBetween(Date value1, Date value2) {
            addCriterion("REVISION_DATE not between", value1, value2, "revisionDate");
            return (Criteria) this;
        }

        public Criteria andRevisionTimeIsNull() {
            addCriterion("REVISION_TIME is null");
            return (Criteria) this;
        }

        public Criteria andRevisionTimeIsNotNull() {
            addCriterion("REVISION_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andRevisionTimeEqualTo(Date value) {
            addCriterion("REVISION_TIME =", value, "revisionTime");
            return (Criteria) this;
        }

        public Criteria andRevisionTimeNotEqualTo(Date value) {
            addCriterion("REVISION_TIME <>", value, "revisionTime");
            return (Criteria) this;
        }

        public Criteria andRevisionTimeGreaterThan(Date value) {
            addCriterion("REVISION_TIME >", value, "revisionTime");
            return (Criteria) this;
        }

        public Criteria andRevisionTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REVISION_TIME >=", value, "revisionTime");
            return (Criteria) this;
        }

        public Criteria andRevisionTimeLessThan(Date value) {
            addCriterion("REVISION_TIME <", value, "revisionTime");
            return (Criteria) this;
        }

        public Criteria andRevisionTimeLessThanOrEqualTo(Date value) {
            addCriterion("REVISION_TIME <=", value, "revisionTime");
            return (Criteria) this;
        }

        public Criteria andRevisionTimeIn(List<Date> values) {
            addCriterion("REVISION_TIME in", values, "revisionTime");
            return (Criteria) this;
        }

        public Criteria andRevisionTimeNotIn(List<Date> values) {
            addCriterion("REVISION_TIME not in", values, "revisionTime");
            return (Criteria) this;
        }

        public Criteria andRevisionTimeBetween(Date value1, Date value2) {
            addCriterion("REVISION_TIME between", value1, value2, "revisionTime");
            return (Criteria) this;
        }

        public Criteria andRevisionTimeNotBetween(Date value1, Date value2) {
            addCriterion("REVISION_TIME not between", value1, value2, "revisionTime");
            return (Criteria) this;
        }

        public Criteria andRevisionOpidIsNull() {
            addCriterion("REVISION_OPID is null");
            return (Criteria) this;
        }

        public Criteria andRevisionOpidIsNotNull() {
            addCriterion("REVISION_OPID is not null");
            return (Criteria) this;
        }

        public Criteria andRevisionOpidEqualTo(String value) {
            addCriterion("REVISION_OPID =", value, "revisionOpid");
            return (Criteria) this;
        }

        public Criteria andRevisionOpidNotEqualTo(String value) {
            addCriterion("REVISION_OPID <>", value, "revisionOpid");
            return (Criteria) this;
        }

        public Criteria andRevisionOpidGreaterThan(String value) {
            addCriterion("REVISION_OPID >", value, "revisionOpid");
            return (Criteria) this;
        }

        public Criteria andRevisionOpidGreaterThanOrEqualTo(String value) {
            addCriterion("REVISION_OPID >=", value, "revisionOpid");
            return (Criteria) this;
        }

        public Criteria andRevisionOpidLessThan(String value) {
            addCriterion("REVISION_OPID <", value, "revisionOpid");
            return (Criteria) this;
        }

        public Criteria andRevisionOpidLessThanOrEqualTo(String value) {
            addCriterion("REVISION_OPID <=", value, "revisionOpid");
            return (Criteria) this;
        }

        public Criteria andRevisionOpidLike(String value) {
            addCriterion("REVISION_OPID like", value, "revisionOpid");
            return (Criteria) this;
        }

        public Criteria andRevisionOpidNotLike(String value) {
            addCriterion("REVISION_OPID not like", value, "revisionOpid");
            return (Criteria) this;
        }

        public Criteria andRevisionOpidIn(List<String> values) {
            addCriterion("REVISION_OPID in", values, "revisionOpid");
            return (Criteria) this;
        }

        public Criteria andRevisionOpidNotIn(List<String> values) {
            addCriterion("REVISION_OPID not in", values, "revisionOpid");
            return (Criteria) this;
        }

        public Criteria andRevisionOpidBetween(String value1, String value2) {
            addCriterion("REVISION_OPID between", value1, value2, "revisionOpid");
            return (Criteria) this;
        }

        public Criteria andRevisionOpidNotBetween(String value1, String value2) {
            addCriterion("REVISION_OPID not between", value1, value2, "revisionOpid");
            return (Criteria) this;
        }

        public Criteria andRevisionTerminalIsNull() {
            addCriterion("REVISION_TERMINAL is null");
            return (Criteria) this;
        }

        public Criteria andRevisionTerminalIsNotNull() {
            addCriterion("REVISION_TERMINAL is not null");
            return (Criteria) this;
        }

        public Criteria andRevisionTerminalEqualTo(String value) {
            addCriterion("REVISION_TERMINAL =", value, "revisionTerminal");
            return (Criteria) this;
        }

        public Criteria andRevisionTerminalNotEqualTo(String value) {
            addCriterion("REVISION_TERMINAL <>", value, "revisionTerminal");
            return (Criteria) this;
        }

        public Criteria andRevisionTerminalGreaterThan(String value) {
            addCriterion("REVISION_TERMINAL >", value, "revisionTerminal");
            return (Criteria) this;
        }

        public Criteria andRevisionTerminalGreaterThanOrEqualTo(String value) {
            addCriterion("REVISION_TERMINAL >=", value, "revisionTerminal");
            return (Criteria) this;
        }

        public Criteria andRevisionTerminalLessThan(String value) {
            addCriterion("REVISION_TERMINAL <", value, "revisionTerminal");
            return (Criteria) this;
        }

        public Criteria andRevisionTerminalLessThanOrEqualTo(String value) {
            addCriterion("REVISION_TERMINAL <=", value, "revisionTerminal");
            return (Criteria) this;
        }

        public Criteria andRevisionTerminalLike(String value) {
            addCriterion("REVISION_TERMINAL like", value, "revisionTerminal");
            return (Criteria) this;
        }

        public Criteria andRevisionTerminalNotLike(String value) {
            addCriterion("REVISION_TERMINAL not like", value, "revisionTerminal");
            return (Criteria) this;
        }

        public Criteria andRevisionTerminalIn(List<String> values) {
            addCriterion("REVISION_TERMINAL in", values, "revisionTerminal");
            return (Criteria) this;
        }

        public Criteria andRevisionTerminalNotIn(List<String> values) {
            addCriterion("REVISION_TERMINAL not in", values, "revisionTerminal");
            return (Criteria) this;
        }

        public Criteria andRevisionTerminalBetween(String value1, String value2) {
            addCriterion("REVISION_TERMINAL between", value1, value2, "revisionTerminal");
            return (Criteria) this;
        }

        public Criteria andRevisionTerminalNotBetween(String value1, String value2) {
            addCriterion("REVISION_TERMINAL not between", value1, value2, "revisionTerminal");
            return (Criteria) this;
        }

        public Criteria andAbtJoinIsNull() {
            addCriterion("ABT_JOIN is null");
            return (Criteria) this;
        }

        public Criteria andAbtJoinIsNotNull() {
            addCriterion("ABT_JOIN is not null");
            return (Criteria) this;
        }

        public Criteria andAbtJoinEqualTo(String value) {
            addCriterion("ABT_JOIN =", value, "abtJoin");
            return (Criteria) this;
        }

        public Criteria andAbtJoinNotEqualTo(String value) {
            addCriterion("ABT_JOIN <>", value, "abtJoin");
            return (Criteria) this;
        }

        public Criteria andAbtJoinGreaterThan(String value) {
            addCriterion("ABT_JOIN >", value, "abtJoin");
            return (Criteria) this;
        }

        public Criteria andAbtJoinGreaterThanOrEqualTo(String value) {
            addCriterion("ABT_JOIN >=", value, "abtJoin");
            return (Criteria) this;
        }

        public Criteria andAbtJoinLessThan(String value) {
            addCriterion("ABT_JOIN <", value, "abtJoin");
            return (Criteria) this;
        }

        public Criteria andAbtJoinLessThanOrEqualTo(String value) {
            addCriterion("ABT_JOIN <=", value, "abtJoin");
            return (Criteria) this;
        }

        public Criteria andAbtJoinLike(String value) {
            addCriterion("ABT_JOIN like", value, "abtJoin");
            return (Criteria) this;
        }

        public Criteria andAbtJoinNotLike(String value) {
            addCriterion("ABT_JOIN not like", value, "abtJoin");
            return (Criteria) this;
        }

        public Criteria andAbtJoinIn(List<String> values) {
            addCriterion("ABT_JOIN in", values, "abtJoin");
            return (Criteria) this;
        }

        public Criteria andAbtJoinNotIn(List<String> values) {
            addCriterion("ABT_JOIN not in", values, "abtJoin");
            return (Criteria) this;
        }

        public Criteria andAbtJoinBetween(String value1, String value2) {
            addCriterion("ABT_JOIN between", value1, value2, "abtJoin");
            return (Criteria) this;
        }

        public Criteria andAbtJoinNotBetween(String value1, String value2) {
            addCriterion("ABT_JOIN not between", value1, value2, "abtJoin");
            return (Criteria) this;
        }

        public Criteria andTrueAcademicYearIsNull() {
            addCriterion("TRUE_ACADEMIC_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andTrueAcademicYearIsNotNull() {
            addCriterion("TRUE_ACADEMIC_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andTrueAcademicYearEqualTo(String value) {
            addCriterion("TRUE_ACADEMIC_YEAR =", value, "trueAcademicYear");
            return (Criteria) this;
        }

        public Criteria andTrueAcademicYearNotEqualTo(String value) {
            addCriterion("TRUE_ACADEMIC_YEAR <>", value, "trueAcademicYear");
            return (Criteria) this;
        }

        public Criteria andTrueAcademicYearGreaterThan(String value) {
            addCriterion("TRUE_ACADEMIC_YEAR >", value, "trueAcademicYear");
            return (Criteria) this;
        }

        public Criteria andTrueAcademicYearGreaterThanOrEqualTo(String value) {
            addCriterion("TRUE_ACADEMIC_YEAR >=", value, "trueAcademicYear");
            return (Criteria) this;
        }

        public Criteria andTrueAcademicYearLessThan(String value) {
            addCriterion("TRUE_ACADEMIC_YEAR <", value, "trueAcademicYear");
            return (Criteria) this;
        }

        public Criteria andTrueAcademicYearLessThanOrEqualTo(String value) {
            addCriterion("TRUE_ACADEMIC_YEAR <=", value, "trueAcademicYear");
            return (Criteria) this;
        }

        public Criteria andTrueAcademicYearLike(String value) {
            addCriterion("TRUE_ACADEMIC_YEAR like", value, "trueAcademicYear");
            return (Criteria) this;
        }

        public Criteria andTrueAcademicYearNotLike(String value) {
            addCriterion("TRUE_ACADEMIC_YEAR not like", value, "trueAcademicYear");
            return (Criteria) this;
        }

        public Criteria andTrueAcademicYearIn(List<String> values) {
            addCriterion("TRUE_ACADEMIC_YEAR in", values, "trueAcademicYear");
            return (Criteria) this;
        }

        public Criteria andTrueAcademicYearNotIn(List<String> values) {
            addCriterion("TRUE_ACADEMIC_YEAR not in", values, "trueAcademicYear");
            return (Criteria) this;
        }

        public Criteria andTrueAcademicYearBetween(String value1, String value2) {
            addCriterion("TRUE_ACADEMIC_YEAR between", value1, value2, "trueAcademicYear");
            return (Criteria) this;
        }

        public Criteria andTrueAcademicYearNotBetween(String value1, String value2) {
            addCriterion("TRUE_ACADEMIC_YEAR not between", value1, value2, "trueAcademicYear");
            return (Criteria) this;
        }

        public Criteria andFinAidYearIsNull() {
            addCriterion("FIN_AID_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andFinAidYearIsNotNull() {
            addCriterion("FIN_AID_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andFinAidYearEqualTo(String value) {
            addCriterion("FIN_AID_YEAR =", value, "finAidYear");
            return (Criteria) this;
        }

        public Criteria andFinAidYearNotEqualTo(String value) {
            addCriterion("FIN_AID_YEAR <>", value, "finAidYear");
            return (Criteria) this;
        }

        public Criteria andFinAidYearGreaterThan(String value) {
            addCriterion("FIN_AID_YEAR >", value, "finAidYear");
            return (Criteria) this;
        }

        public Criteria andFinAidYearGreaterThanOrEqualTo(String value) {
            addCriterion("FIN_AID_YEAR >=", value, "finAidYear");
            return (Criteria) this;
        }

        public Criteria andFinAidYearLessThan(String value) {
            addCriterion("FIN_AID_YEAR <", value, "finAidYear");
            return (Criteria) this;
        }

        public Criteria andFinAidYearLessThanOrEqualTo(String value) {
            addCriterion("FIN_AID_YEAR <=", value, "finAidYear");
            return (Criteria) this;
        }

        public Criteria andFinAidYearLike(String value) {
            addCriterion("FIN_AID_YEAR like", value, "finAidYear");
            return (Criteria) this;
        }

        public Criteria andFinAidYearNotLike(String value) {
            addCriterion("FIN_AID_YEAR not like", value, "finAidYear");
            return (Criteria) this;
        }

        public Criteria andFinAidYearIn(List<String> values) {
            addCriterion("FIN_AID_YEAR in", values, "finAidYear");
            return (Criteria) this;
        }

        public Criteria andFinAidYearNotIn(List<String> values) {
            addCriterion("FIN_AID_YEAR not in", values, "finAidYear");
            return (Criteria) this;
        }

        public Criteria andFinAidYearBetween(String value1, String value2) {
            addCriterion("FIN_AID_YEAR between", value1, value2, "finAidYear");
            return (Criteria) this;
        }

        public Criteria andFinAidYearNotBetween(String value1, String value2) {
            addCriterion("FIN_AID_YEAR not between", value1, value2, "finAidYear");
            return (Criteria) this;
        }

        public Criteria andFinAidTermIsNull() {
            addCriterion("FIN_AID_TERM is null");
            return (Criteria) this;
        }

        public Criteria andFinAidTermIsNotNull() {
            addCriterion("FIN_AID_TERM is not null");
            return (Criteria) this;
        }

        public Criteria andFinAidTermEqualTo(String value) {
            addCriterion("FIN_AID_TERM =", value, "finAidTerm");
            return (Criteria) this;
        }

        public Criteria andFinAidTermNotEqualTo(String value) {
            addCriterion("FIN_AID_TERM <>", value, "finAidTerm");
            return (Criteria) this;
        }

        public Criteria andFinAidTermGreaterThan(String value) {
            addCriterion("FIN_AID_TERM >", value, "finAidTerm");
            return (Criteria) this;
        }

        public Criteria andFinAidTermGreaterThanOrEqualTo(String value) {
            addCriterion("FIN_AID_TERM >=", value, "finAidTerm");
            return (Criteria) this;
        }

        public Criteria andFinAidTermLessThan(String value) {
            addCriterion("FIN_AID_TERM <", value, "finAidTerm");
            return (Criteria) this;
        }

        public Criteria andFinAidTermLessThanOrEqualTo(String value) {
            addCriterion("FIN_AID_TERM <=", value, "finAidTerm");
            return (Criteria) this;
        }

        public Criteria andFinAidTermLike(String value) {
            addCriterion("FIN_AID_TERM like", value, "finAidTerm");
            return (Criteria) this;
        }

        public Criteria andFinAidTermNotLike(String value) {
            addCriterion("FIN_AID_TERM not like", value, "finAidTerm");
            return (Criteria) this;
        }

        public Criteria andFinAidTermIn(List<String> values) {
            addCriterion("FIN_AID_TERM in", values, "finAidTerm");
            return (Criteria) this;
        }

        public Criteria andFinAidTermNotIn(List<String> values) {
            addCriterion("FIN_AID_TERM not in", values, "finAidTerm");
            return (Criteria) this;
        }

        public Criteria andFinAidTermBetween(String value1, String value2) {
            addCriterion("FIN_AID_TERM between", value1, value2, "finAidTerm");
            return (Criteria) this;
        }

        public Criteria andFinAidTermNotBetween(String value1, String value2) {
            addCriterion("FIN_AID_TERM not between", value1, value2, "finAidTerm");
            return (Criteria) this;
        }

        public Criteria andMidStartDateIsNull() {
            addCriterion("MID_START_DATE is null");
            return (Criteria) this;
        }

        public Criteria andMidStartDateIsNotNull() {
            addCriterion("MID_START_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andMidStartDateEqualTo(Date value) {
            addCriterion("MID_START_DATE =", value, "midStartDate");
            return (Criteria) this;
        }

        public Criteria andMidStartDateNotEqualTo(Date value) {
            addCriterion("MID_START_DATE <>", value, "midStartDate");
            return (Criteria) this;
        }

        public Criteria andMidStartDateGreaterThan(Date value) {
            addCriterion("MID_START_DATE >", value, "midStartDate");
            return (Criteria) this;
        }

        public Criteria andMidStartDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MID_START_DATE >=", value, "midStartDate");
            return (Criteria) this;
        }

        public Criteria andMidStartDateLessThan(Date value) {
            addCriterion("MID_START_DATE <", value, "midStartDate");
            return (Criteria) this;
        }

        public Criteria andMidStartDateLessThanOrEqualTo(Date value) {
            addCriterion("MID_START_DATE <=", value, "midStartDate");
            return (Criteria) this;
        }

        public Criteria andMidStartDateIn(List<Date> values) {
            addCriterion("MID_START_DATE in", values, "midStartDate");
            return (Criteria) this;
        }

        public Criteria andMidStartDateNotIn(List<Date> values) {
            addCriterion("MID_START_DATE not in", values, "midStartDate");
            return (Criteria) this;
        }

        public Criteria andMidStartDateBetween(Date value1, Date value2) {
            addCriterion("MID_START_DATE between", value1, value2, "midStartDate");
            return (Criteria) this;
        }

        public Criteria andMidStartDateNotBetween(Date value1, Date value2) {
            addCriterion("MID_START_DATE not between", value1, value2, "midStartDate");
            return (Criteria) this;
        }

        public Criteria andMidEndDateIsNull() {
            addCriterion("MID_END_DATE is null");
            return (Criteria) this;
        }

        public Criteria andMidEndDateIsNotNull() {
            addCriterion("MID_END_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andMidEndDateEqualTo(Date value) {
            addCriterion("MID_END_DATE =", value, "midEndDate");
            return (Criteria) this;
        }

        public Criteria andMidEndDateNotEqualTo(Date value) {
            addCriterion("MID_END_DATE <>", value, "midEndDate");
            return (Criteria) this;
        }

        public Criteria andMidEndDateGreaterThan(Date value) {
            addCriterion("MID_END_DATE >", value, "midEndDate");
            return (Criteria) this;
        }

        public Criteria andMidEndDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MID_END_DATE >=", value, "midEndDate");
            return (Criteria) this;
        }

        public Criteria andMidEndDateLessThan(Date value) {
            addCriterion("MID_END_DATE <", value, "midEndDate");
            return (Criteria) this;
        }

        public Criteria andMidEndDateLessThanOrEqualTo(Date value) {
            addCriterion("MID_END_DATE <=", value, "midEndDate");
            return (Criteria) this;
        }

        public Criteria andMidEndDateIn(List<Date> values) {
            addCriterion("MID_END_DATE in", values, "midEndDate");
            return (Criteria) this;
        }

        public Criteria andMidEndDateNotIn(List<Date> values) {
            addCriterion("MID_END_DATE not in", values, "midEndDate");
            return (Criteria) this;
        }

        public Criteria andMidEndDateBetween(Date value1, Date value2) {
            addCriterion("MID_END_DATE between", value1, value2, "midEndDate");
            return (Criteria) this;
        }

        public Criteria andMidEndDateNotBetween(Date value1, Date value2) {
            addCriterion("MID_END_DATE not between", value1, value2, "midEndDate");
            return (Criteria) this;
        }

        public Criteria andFinalStartDateIsNull() {
            addCriterion("FINAL_START_DATE is null");
            return (Criteria) this;
        }

        public Criteria andFinalStartDateIsNotNull() {
            addCriterion("FINAL_START_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andFinalStartDateEqualTo(Date value) {
            addCriterion("FINAL_START_DATE =", value, "finalStartDate");
            return (Criteria) this;
        }

        public Criteria andFinalStartDateNotEqualTo(Date value) {
            addCriterion("FINAL_START_DATE <>", value, "finalStartDate");
            return (Criteria) this;
        }

        public Criteria andFinalStartDateGreaterThan(Date value) {
            addCriterion("FINAL_START_DATE >", value, "finalStartDate");
            return (Criteria) this;
        }

        public Criteria andFinalStartDateGreaterThanOrEqualTo(Date value) {
            addCriterion("FINAL_START_DATE >=", value, "finalStartDate");
            return (Criteria) this;
        }

        public Criteria andFinalStartDateLessThan(Date value) {
            addCriterion("FINAL_START_DATE <", value, "finalStartDate");
            return (Criteria) this;
        }

        public Criteria andFinalStartDateLessThanOrEqualTo(Date value) {
            addCriterion("FINAL_START_DATE <=", value, "finalStartDate");
            return (Criteria) this;
        }

        public Criteria andFinalStartDateIn(List<Date> values) {
            addCriterion("FINAL_START_DATE in", values, "finalStartDate");
            return (Criteria) this;
        }

        public Criteria andFinalStartDateNotIn(List<Date> values) {
            addCriterion("FINAL_START_DATE not in", values, "finalStartDate");
            return (Criteria) this;
        }

        public Criteria andFinalStartDateBetween(Date value1, Date value2) {
            addCriterion("FINAL_START_DATE between", value1, value2, "finalStartDate");
            return (Criteria) this;
        }

        public Criteria andFinalStartDateNotBetween(Date value1, Date value2) {
            addCriterion("FINAL_START_DATE not between", value1, value2, "finalStartDate");
            return (Criteria) this;
        }

        public Criteria andFinalEndDateIsNull() {
            addCriterion("FINAL_END_DATE is null");
            return (Criteria) this;
        }

        public Criteria andFinalEndDateIsNotNull() {
            addCriterion("FINAL_END_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andFinalEndDateEqualTo(Date value) {
            addCriterion("FINAL_END_DATE =", value, "finalEndDate");
            return (Criteria) this;
        }

        public Criteria andFinalEndDateNotEqualTo(Date value) {
            addCriterion("FINAL_END_DATE <>", value, "finalEndDate");
            return (Criteria) this;
        }

        public Criteria andFinalEndDateGreaterThan(Date value) {
            addCriterion("FINAL_END_DATE >", value, "finalEndDate");
            return (Criteria) this;
        }

        public Criteria andFinalEndDateGreaterThanOrEqualTo(Date value) {
            addCriterion("FINAL_END_DATE >=", value, "finalEndDate");
            return (Criteria) this;
        }

        public Criteria andFinalEndDateLessThan(Date value) {
            addCriterion("FINAL_END_DATE <", value, "finalEndDate");
            return (Criteria) this;
        }

        public Criteria andFinalEndDateLessThanOrEqualTo(Date value) {
            addCriterion("FINAL_END_DATE <=", value, "finalEndDate");
            return (Criteria) this;
        }

        public Criteria andFinalEndDateIn(List<Date> values) {
            addCriterion("FINAL_END_DATE in", values, "finalEndDate");
            return (Criteria) this;
        }

        public Criteria andFinalEndDateNotIn(List<Date> values) {
            addCriterion("FINAL_END_DATE not in", values, "finalEndDate");
            return (Criteria) this;
        }

        public Criteria andFinalEndDateBetween(Date value1, Date value2) {
            addCriterion("FINAL_END_DATE between", value1, value2, "finalEndDate");
            return (Criteria) this;
        }

        public Criteria andFinalEndDateNotBetween(Date value1, Date value2) {
            addCriterion("FINAL_END_DATE not between", value1, value2, "finalEndDate");
            return (Criteria) this;
        }

        public Criteria andSessionperiodidIsNull() {
            addCriterion("SessionPeriodId is null");
            return (Criteria) this;
        }

        public Criteria andSessionperiodidIsNotNull() {
            addCriterion("SessionPeriodId is not null");
            return (Criteria) this;
        }

        public Criteria andSessionperiodidEqualTo(Integer value) {
            addCriterion("SessionPeriodId =", value, "sessionperiodid");
            return (Criteria) this;
        }

        public Criteria andSessionperiodidNotEqualTo(Integer value) {
            addCriterion("SessionPeriodId <>", value, "sessionperiodid");
            return (Criteria) this;
        }

        public Criteria andSessionperiodidGreaterThan(Integer value) {
            addCriterion("SessionPeriodId >", value, "sessionperiodid");
            return (Criteria) this;
        }

        public Criteria andSessionperiodidGreaterThanOrEqualTo(Integer value) {
            addCriterion("SessionPeriodId >=", value, "sessionperiodid");
            return (Criteria) this;
        }

        public Criteria andSessionperiodidLessThan(Integer value) {
            addCriterion("SessionPeriodId <", value, "sessionperiodid");
            return (Criteria) this;
        }

        public Criteria andSessionperiodidLessThanOrEqualTo(Integer value) {
            addCriterion("SessionPeriodId <=", value, "sessionperiodid");
            return (Criteria) this;
        }

        public Criteria andSessionperiodidIn(List<Integer> values) {
            addCriterion("SessionPeriodId in", values, "sessionperiodid");
            return (Criteria) this;
        }

        public Criteria andSessionperiodidNotIn(List<Integer> values) {
            addCriterion("SessionPeriodId not in", values, "sessionperiodid");
            return (Criteria) this;
        }

        public Criteria andSessionperiodidBetween(Integer value1, Integer value2) {
            addCriterion("SessionPeriodId between", value1, value2, "sessionperiodid");
            return (Criteria) this;
        }

        public Criteria andSessionperiodidNotBetween(Integer value1, Integer value2) {
            addCriterion("SessionPeriodId not between", value1, value2, "sessionperiodid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 04 11:08:45 CDT 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}