package com.ritchey.simple.domain.powercampus;

import java.io.Serializable;
import java.util.Date;

import com.ritchey.simple.domain.chapel.Reflect;

public class AcademicCalendar extends AcademicCalendarKey implements Reflect, Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.START_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.END_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.FISCAL_YEAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private String fiscalYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.ACADEMIC_WEEKS
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private Integer academicWeeks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.ACADEMIC_MONTHS
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private Integer academicMonths;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.NUMBER_COURSES
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private Integer numberCourses;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.PRE_REG_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private Date preRegDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.REG_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private Date regDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.LAST_REG_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private Date lastRegDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.GRADE_WTHDRWL_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private Date gradeWthdrwlDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.GRADE_PENALTY_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private Date gradePenaltyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.CREATE_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.CREATE_TIME
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.CREATE_OPID
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private String createOpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.CREATE_TERMINAL
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private String createTerminal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.REVISION_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private Date revisionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.REVISION_TIME
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private Date revisionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.REVISION_OPID
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private String revisionOpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.REVISION_TERMINAL
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private String revisionTerminal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.ABT_JOIN
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private String abtJoin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.TRUE_ACADEMIC_YEAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private String trueAcademicYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.FIN_AID_YEAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private String finAidYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.FIN_AID_TERM
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private String finAidTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.MID_START_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private Date midStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.MID_END_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private Date midEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.FINAL_START_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private Date finalStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.FINAL_END_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private Date finalEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACADEMICCALENDAR.SessionPeriodId
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private Integer sessionperiodid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    private static final long serialVersionUID = 20130904110845L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.START_DATE
     *
     * @return the value of ACADEMICCALENDAR.START_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.START_DATE
     *
     * @param startDate the value for ACADEMICCALENDAR.START_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.END_DATE
     *
     * @return the value of ACADEMICCALENDAR.END_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.END_DATE
     *
     * @param endDate the value for ACADEMICCALENDAR.END_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.FISCAL_YEAR
     *
     * @return the value of ACADEMICCALENDAR.FISCAL_YEAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public String getFiscalYear() {
        return fiscalYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.FISCAL_YEAR
     *
     * @param fiscalYear the value for ACADEMICCALENDAR.FISCAL_YEAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setFiscalYear(String fiscalYear) {
        this.fiscalYear = fiscalYear == null ? null : fiscalYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.ACADEMIC_WEEKS
     *
     * @return the value of ACADEMICCALENDAR.ACADEMIC_WEEKS
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public Integer getAcademicWeeks() {
        return academicWeeks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.ACADEMIC_WEEKS
     *
     * @param academicWeeks the value for ACADEMICCALENDAR.ACADEMIC_WEEKS
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setAcademicWeeks(Integer academicWeeks) {
        this.academicWeeks = academicWeeks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.ACADEMIC_MONTHS
     *
     * @return the value of ACADEMICCALENDAR.ACADEMIC_MONTHS
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public Integer getAcademicMonths() {
        return academicMonths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.ACADEMIC_MONTHS
     *
     * @param academicMonths the value for ACADEMICCALENDAR.ACADEMIC_MONTHS
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setAcademicMonths(Integer academicMonths) {
        this.academicMonths = academicMonths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.NUMBER_COURSES
     *
     * @return the value of ACADEMICCALENDAR.NUMBER_COURSES
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public Integer getNumberCourses() {
        return numberCourses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.NUMBER_COURSES
     *
     * @param numberCourses the value for ACADEMICCALENDAR.NUMBER_COURSES
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setNumberCourses(Integer numberCourses) {
        this.numberCourses = numberCourses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.PRE_REG_DATE
     *
     * @return the value of ACADEMICCALENDAR.PRE_REG_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public Date getPreRegDate() {
        return preRegDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.PRE_REG_DATE
     *
     * @param preRegDate the value for ACADEMICCALENDAR.PRE_REG_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setPreRegDate(Date preRegDate) {
        this.preRegDate = preRegDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.REG_DATE
     *
     * @return the value of ACADEMICCALENDAR.REG_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.REG_DATE
     *
     * @param regDate the value for ACADEMICCALENDAR.REG_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.LAST_REG_DATE
     *
     * @return the value of ACADEMICCALENDAR.LAST_REG_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public Date getLastRegDate() {
        return lastRegDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.LAST_REG_DATE
     *
     * @param lastRegDate the value for ACADEMICCALENDAR.LAST_REG_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setLastRegDate(Date lastRegDate) {
        this.lastRegDate = lastRegDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.GRADE_WTHDRWL_DATE
     *
     * @return the value of ACADEMICCALENDAR.GRADE_WTHDRWL_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public Date getGradeWthdrwlDate() {
        return gradeWthdrwlDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.GRADE_WTHDRWL_DATE
     *
     * @param gradeWthdrwlDate the value for ACADEMICCALENDAR.GRADE_WTHDRWL_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setGradeWthdrwlDate(Date gradeWthdrwlDate) {
        this.gradeWthdrwlDate = gradeWthdrwlDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.GRADE_PENALTY_DATE
     *
     * @return the value of ACADEMICCALENDAR.GRADE_PENALTY_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public Date getGradePenaltyDate() {
        return gradePenaltyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.GRADE_PENALTY_DATE
     *
     * @param gradePenaltyDate the value for ACADEMICCALENDAR.GRADE_PENALTY_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setGradePenaltyDate(Date gradePenaltyDate) {
        this.gradePenaltyDate = gradePenaltyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.CREATE_DATE
     *
     * @return the value of ACADEMICCALENDAR.CREATE_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.CREATE_DATE
     *
     * @param createDate the value for ACADEMICCALENDAR.CREATE_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.CREATE_TIME
     *
     * @return the value of ACADEMICCALENDAR.CREATE_TIME
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.CREATE_TIME
     *
     * @param createTime the value for ACADEMICCALENDAR.CREATE_TIME
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.CREATE_OPID
     *
     * @return the value of ACADEMICCALENDAR.CREATE_OPID
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public String getCreateOpid() {
        return createOpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.CREATE_OPID
     *
     * @param createOpid the value for ACADEMICCALENDAR.CREATE_OPID
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setCreateOpid(String createOpid) {
        this.createOpid = createOpid == null ? null : createOpid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.CREATE_TERMINAL
     *
     * @return the value of ACADEMICCALENDAR.CREATE_TERMINAL
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public String getCreateTerminal() {
        return createTerminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.CREATE_TERMINAL
     *
     * @param createTerminal the value for ACADEMICCALENDAR.CREATE_TERMINAL
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setCreateTerminal(String createTerminal) {
        this.createTerminal = createTerminal == null ? null : createTerminal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.REVISION_DATE
     *
     * @return the value of ACADEMICCALENDAR.REVISION_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public Date getRevisionDate() {
        return revisionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.REVISION_DATE
     *
     * @param revisionDate the value for ACADEMICCALENDAR.REVISION_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setRevisionDate(Date revisionDate) {
        this.revisionDate = revisionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.REVISION_TIME
     *
     * @return the value of ACADEMICCALENDAR.REVISION_TIME
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public Date getRevisionTime() {
        return revisionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.REVISION_TIME
     *
     * @param revisionTime the value for ACADEMICCALENDAR.REVISION_TIME
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setRevisionTime(Date revisionTime) {
        this.revisionTime = revisionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.REVISION_OPID
     *
     * @return the value of ACADEMICCALENDAR.REVISION_OPID
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public String getRevisionOpid() {
        return revisionOpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.REVISION_OPID
     *
     * @param revisionOpid the value for ACADEMICCALENDAR.REVISION_OPID
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setRevisionOpid(String revisionOpid) {
        this.revisionOpid = revisionOpid == null ? null : revisionOpid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.REVISION_TERMINAL
     *
     * @return the value of ACADEMICCALENDAR.REVISION_TERMINAL
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public String getRevisionTerminal() {
        return revisionTerminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.REVISION_TERMINAL
     *
     * @param revisionTerminal the value for ACADEMICCALENDAR.REVISION_TERMINAL
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setRevisionTerminal(String revisionTerminal) {
        this.revisionTerminal = revisionTerminal == null ? null : revisionTerminal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.ABT_JOIN
     *
     * @return the value of ACADEMICCALENDAR.ABT_JOIN
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public String getAbtJoin() {
        return abtJoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.ABT_JOIN
     *
     * @param abtJoin the value for ACADEMICCALENDAR.ABT_JOIN
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setAbtJoin(String abtJoin) {
        this.abtJoin = abtJoin == null ? null : abtJoin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.TRUE_ACADEMIC_YEAR
     *
     * @return the value of ACADEMICCALENDAR.TRUE_ACADEMIC_YEAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public String getTrueAcademicYear() {
        return trueAcademicYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.TRUE_ACADEMIC_YEAR
     *
     * @param trueAcademicYear the value for ACADEMICCALENDAR.TRUE_ACADEMIC_YEAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setTrueAcademicYear(String trueAcademicYear) {
        this.trueAcademicYear = trueAcademicYear == null ? null : trueAcademicYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.FIN_AID_YEAR
     *
     * @return the value of ACADEMICCALENDAR.FIN_AID_YEAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public String getFinAidYear() {
        return finAidYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.FIN_AID_YEAR
     *
     * @param finAidYear the value for ACADEMICCALENDAR.FIN_AID_YEAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setFinAidYear(String finAidYear) {
        this.finAidYear = finAidYear == null ? null : finAidYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.FIN_AID_TERM
     *
     * @return the value of ACADEMICCALENDAR.FIN_AID_TERM
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public String getFinAidTerm() {
        return finAidTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.FIN_AID_TERM
     *
     * @param finAidTerm the value for ACADEMICCALENDAR.FIN_AID_TERM
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setFinAidTerm(String finAidTerm) {
        this.finAidTerm = finAidTerm == null ? null : finAidTerm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.MID_START_DATE
     *
     * @return the value of ACADEMICCALENDAR.MID_START_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public Date getMidStartDate() {
        return midStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.MID_START_DATE
     *
     * @param midStartDate the value for ACADEMICCALENDAR.MID_START_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setMidStartDate(Date midStartDate) {
        this.midStartDate = midStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.MID_END_DATE
     *
     * @return the value of ACADEMICCALENDAR.MID_END_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public Date getMidEndDate() {
        return midEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.MID_END_DATE
     *
     * @param midEndDate the value for ACADEMICCALENDAR.MID_END_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setMidEndDate(Date midEndDate) {
        this.midEndDate = midEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.FINAL_START_DATE
     *
     * @return the value of ACADEMICCALENDAR.FINAL_START_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public Date getFinalStartDate() {
        return finalStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.FINAL_START_DATE
     *
     * @param finalStartDate the value for ACADEMICCALENDAR.FINAL_START_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setFinalStartDate(Date finalStartDate) {
        this.finalStartDate = finalStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.FINAL_END_DATE
     *
     * @return the value of ACADEMICCALENDAR.FINAL_END_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public Date getFinalEndDate() {
        return finalEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.FINAL_END_DATE
     *
     * @param finalEndDate the value for ACADEMICCALENDAR.FINAL_END_DATE
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setFinalEndDate(Date finalEndDate) {
        this.finalEndDate = finalEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACADEMICCALENDAR.SessionPeriodId
     *
     * @return the value of ACADEMICCALENDAR.SessionPeriodId
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public Integer getSessionperiodid() {
        return sessionperiodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACADEMICCALENDAR.SessionPeriodId
     *
     * @param sessionperiodid the value for ACADEMICCALENDAR.SessionPeriodId
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    public void setSessionperiodid(Integer sessionperiodid) {
        this.sessionperiodid = sessionperiodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getName());
        sb.append("[");
        sb.append("Hash = ").append(hashCode());
        sb.append(",startDate=").append(startDate);
        sb.append(",endDate=").append(endDate);
        sb.append(",fiscalYear=").append(fiscalYear);
        sb.append(",academicWeeks=").append(academicWeeks);
        sb.append(",academicMonths=").append(academicMonths);
        sb.append(",numberCourses=").append(numberCourses);
        sb.append(",preRegDate=").append(preRegDate);
        sb.append(",regDate=").append(regDate);
        sb.append(",lastRegDate=").append(lastRegDate);
        sb.append(",gradeWthdrwlDate=").append(gradeWthdrwlDate);
        sb.append(",gradePenaltyDate=").append(gradePenaltyDate);
        sb.append(",createDate=").append(createDate);
        sb.append(",createTime=").append(createTime);
        sb.append(",createOpid=").append(createOpid);
        sb.append(",createTerminal=").append(createTerminal);
        sb.append(",revisionDate=").append(revisionDate);
        sb.append(",revisionTime=").append(revisionTime);
        sb.append(",revisionOpid=").append(revisionOpid);
        sb.append(",revisionTerminal=").append(revisionTerminal);
        sb.append(",abtJoin=").append(abtJoin);
        sb.append(",trueAcademicYear=").append(trueAcademicYear);
        sb.append(",finAidYear=").append(finAidYear);
        sb.append(",finAidTerm=").append(finAidTerm);
        sb.append(",midStartDate=").append(midStartDate);
        sb.append(",midEndDate=").append(midEndDate);
        sb.append(",finalStartDate=").append(finalStartDate);
        sb.append(",finalEndDate=").append(finalEndDate);
        sb.append(",sessionperiodid=").append(sessionperiodid);
        sb.append(",serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    @Override
    public Object get(String name) {
        if (name.equals("startDate")) return startDate;
        if (name.equals("endDate")) return endDate;
        if (name.equals("fiscalYear")) return fiscalYear;
        if (name.equals("academicWeeks")) return academicWeeks;
        if (name.equals("academicMonths")) return academicMonths;
        if (name.equals("numberCourses")) return numberCourses;
        if (name.equals("preRegDate")) return preRegDate;
        if (name.equals("regDate")) return regDate;
        if (name.equals("lastRegDate")) return lastRegDate;
        if (name.equals("gradeWthdrwlDate")) return gradeWthdrwlDate;
        if (name.equals("gradePenaltyDate")) return gradePenaltyDate;
        if (name.equals("createDate")) return createDate;
        if (name.equals("createTime")) return createTime;
        if (name.equals("createOpid")) return createOpid;
        if (name.equals("createTerminal")) return createTerminal;
        if (name.equals("revisionDate")) return revisionDate;
        if (name.equals("revisionTime")) return revisionTime;
        if (name.equals("revisionOpid")) return revisionOpid;
        if (name.equals("revisionTerminal")) return revisionTerminal;
        if (name.equals("abtJoin")) return abtJoin;
        if (name.equals("trueAcademicYear")) return trueAcademicYear;
        if (name.equals("finAidYear")) return finAidYear;
        if (name.equals("finAidTerm")) return finAidTerm;
        if (name.equals("midStartDate")) return midStartDate;
        if (name.equals("midEndDate")) return midEndDate;
        if (name.equals("finalStartDate")) return finalStartDate;
        if (name.equals("finalEndDate")) return finalEndDate;
        if (name.equals("sessionperiodid")) return sessionperiodid;
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    @Override
    public void set(String name, Object value) {
        if (name.equals("startDate")) startDate = value==null?null:(java.util.Date) value;
        if (name.equals("endDate")) endDate = value==null?null:(java.util.Date) value;
        if (name.equals("fiscalYear")) fiscalYear = value==null?null:(java.lang.String) value;
        if (name.equals("academicWeeks")) academicWeeks = value==null?null:(java.lang.Integer) value;
        if (name.equals("academicMonths")) academicMonths = value==null?null:(java.lang.Integer) value;
        if (name.equals("numberCourses")) numberCourses = value==null?null:(java.lang.Integer) value;
        if (name.equals("preRegDate")) preRegDate = value==null?null:(java.util.Date) value;
        if (name.equals("regDate")) regDate = value==null?null:(java.util.Date) value;
        if (name.equals("lastRegDate")) lastRegDate = value==null?null:(java.util.Date) value;
        if (name.equals("gradeWthdrwlDate")) gradeWthdrwlDate = value==null?null:(java.util.Date) value;
        if (name.equals("gradePenaltyDate")) gradePenaltyDate = value==null?null:(java.util.Date) value;
        if (name.equals("createDate")) createDate = value==null?null:(java.util.Date) value;
        if (name.equals("createTime")) createTime = value==null?null:(java.util.Date) value;
        if (name.equals("createOpid")) createOpid = value==null?null:(java.lang.String) value;
        if (name.equals("createTerminal")) createTerminal = value==null?null:(java.lang.String) value;
        if (name.equals("revisionDate")) revisionDate = value==null?null:(java.util.Date) value;
        if (name.equals("revisionTime")) revisionTime = value==null?null:(java.util.Date) value;
        if (name.equals("revisionOpid")) revisionOpid = value==null?null:(java.lang.String) value;
        if (name.equals("revisionTerminal")) revisionTerminal = value==null?null:(java.lang.String) value;
        if (name.equals("abtJoin")) abtJoin = value==null?null:(java.lang.String) value;
        if (name.equals("trueAcademicYear")) trueAcademicYear = value==null?null:(java.lang.String) value;
        if (name.equals("finAidYear")) finAidYear = value==null?null:(java.lang.String) value;
        if (name.equals("finAidTerm")) finAidTerm = value==null?null:(java.lang.String) value;
        if (name.equals("midStartDate")) midStartDate = value==null?null:(java.util.Date) value;
        if (name.equals("midEndDate")) midEndDate = value==null?null:(java.util.Date) value;
        if (name.equals("finalStartDate")) finalStartDate = value==null?null:(java.util.Date) value;
        if (name.equals("finalEndDate")) finalEndDate = value==null?null:(java.util.Date) value;
        if (name.equals("sessionperiodid")) sessionperiodid = value==null?null:(java.lang.Integer) value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACADEMICCALENDAR
     *
     * @mbggenerated Wed Sep 04 11:08:45 CDT 2013
     */
    @Override
    public void copy(Object a) {
        AcademicCalendar castObject = (AcademicCalendar) a;
        this.startDate = castObject.startDate;
        this.endDate = castObject.endDate;
        this.fiscalYear = castObject.fiscalYear;
        this.academicWeeks = castObject.academicWeeks;
        this.academicMonths = castObject.academicMonths;
        this.numberCourses = castObject.numberCourses;
        this.preRegDate = castObject.preRegDate;
        this.regDate = castObject.regDate;
        this.lastRegDate = castObject.lastRegDate;
        this.gradeWthdrwlDate = castObject.gradeWthdrwlDate;
        this.gradePenaltyDate = castObject.gradePenaltyDate;
        this.createDate = castObject.createDate;
        this.createTime = castObject.createTime;
        this.createOpid = castObject.createOpid;
        this.createTerminal = castObject.createTerminal;
        this.revisionDate = castObject.revisionDate;
        this.revisionTime = castObject.revisionTime;
        this.revisionOpid = castObject.revisionOpid;
        this.revisionTerminal = castObject.revisionTerminal;
        this.abtJoin = castObject.abtJoin;
        this.trueAcademicYear = castObject.trueAcademicYear;
        this.finAidYear = castObject.finAidYear;
        this.finAidTerm = castObject.finAidTerm;
        this.midStartDate = castObject.midStartDate;
        this.midEndDate = castObject.midEndDate;
        this.finalStartDate = castObject.finalStartDate;
        this.finalEndDate = castObject.finalEndDate;
        this.sessionperiodid = castObject.sessionperiodid;
    }

    public String simpleName() {
        return "AcademicCalendar";
    }
}