package com.ritchey.simple.domain.chapel;

import java.io.Serializable;

public class ChapelPerson implements Reflect, Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.id
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.people_id
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    private String peopleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.lastName
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    private String lastname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.firstName
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    private String firstname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.middleName
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    private String middlename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.currentStudent
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    private Boolean currentstudent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.email
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    private static final long serialVersionUID = 20140828153849L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.id
     *
     * @return the value of person.id
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.id
     *
     * @param id the value for person.id
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.people_id
     *
     * @return the value of person.people_id
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    public String getPeopleId() {
        return peopleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.people_id
     *
     * @param peopleId the value for person.people_id
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    public void setPeopleId(String peopleId) {
        this.peopleId = peopleId == null ? null : peopleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.lastName
     *
     * @return the value of person.lastName
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.lastName
     *
     * @param lastname the value for person.lastName
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    public void setLastname(String lastname) {
        this.lastname = lastname == null ? null : lastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.firstName
     *
     * @return the value of person.firstName
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.firstName
     *
     * @param firstname the value for person.firstName
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname == null ? null : firstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.middleName
     *
     * @return the value of person.middleName
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    public String getMiddlename() {
        return middlename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.middleName
     *
     * @param middlename the value for person.middleName
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    public void setMiddlename(String middlename) {
        this.middlename = middlename == null ? null : middlename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.currentStudent
     *
     * @return the value of person.currentStudent
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    public Boolean getCurrentstudent() {
        return currentstudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.currentStudent
     *
     * @param currentstudent the value for person.currentStudent
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    public void setCurrentstudent(Boolean currentstudent) {
        this.currentstudent = currentstudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.email
     *
     * @return the value of person.email
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.email
     *
     * @param email the value for person.email
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getName());
        sb.append("[");
        sb.append("Hash = ").append(hashCode());
        sb.append(",id=").append(id);
        sb.append(",peopleId=").append(peopleId);
        sb.append(",lastname=").append(lastname);
        sb.append(",firstname=").append(firstname);
        sb.append(",middlename=").append(middlename);
        sb.append(",currentstudent=").append(currentstudent);
        sb.append(",email=").append(email);
        sb.append(",serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    @Override
    public Object get(String name) {
        if (name.equals("id")) return id;
        if (name.equals("peopleId")) return peopleId;
        if (name.equals("lastname")) return lastname;
        if (name.equals("firstname")) return firstname;
        if (name.equals("middlename")) return middlename;
        if (name.equals("currentstudent")) return currentstudent;
        if (name.equals("email")) return email;
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    @Override
    public void set(String name, Object value) {
        if (name.equals("id")) id = value==null?null:(java.lang.Integer) value;
        if (name.equals("peopleId")) peopleId = value==null?null:(java.lang.String) value;
        if (name.equals("lastname")) lastname = value==null?null:(java.lang.String) value;
        if (name.equals("firstname")) firstname = value==null?null:(java.lang.String) value;
        if (name.equals("middlename")) middlename = value==null?null:(java.lang.String) value;
        if (name.equals("currentstudent")) currentstudent = value==null?null:(java.lang.Boolean) value;
        if (name.equals("email")) email = value==null?null:(java.lang.String) value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Thu Aug 28 15:38:49 CDT 2014
     */
    @Override
    public void copy(Object a) {
        ChapelPerson castObject = (ChapelPerson) a;
        this.id = castObject.id;
        this.peopleId = castObject.peopleId;
        this.lastname = castObject.lastname;
        this.firstname = castObject.firstname;
        this.middlename = castObject.middlename;
        this.currentstudent = castObject.currentstudent;
        this.email = castObject.email;
    }

    public String simpleName() {
        return "ChapelPerson";
    }
}