package com.ritchey.simple.domain.chapel;

import java.io.Serializable;
import java.sql.Date;

public class Exemptions implements Reflect, Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exemptions.id
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exemptions.personId
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    private Integer personid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exemptions.endTerm
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    private Date endterm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exemptions.exempt
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    private Integer exempt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exemptions.comment
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exemptions
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    private static final long serialVersionUID = 20140828140753L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exemptions.id
     *
     * @return the value of exemptions.id
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exemptions.id
     *
     * @param id the value for exemptions.id
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exemptions.personId
     *
     * @return the value of exemptions.personId
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    public Integer getPersonid() {
        return personid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exemptions.personId
     *
     * @param personid the value for exemptions.personId
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    public void setPersonid(Integer personid) {
        this.personid = personid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exemptions.endTerm
     *
     * @return the value of exemptions.endTerm
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    public Date getEndterm() {
        return endterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exemptions.endTerm
     *
     * @param endterm the value for exemptions.endTerm
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    public void setEndterm(Date endterm) {
        this.endterm = endterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exemptions.exempt
     *
     * @return the value of exemptions.exempt
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    public Integer getExempt() {
        return exempt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exemptions.exempt
     *
     * @param exempt the value for exemptions.exempt
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    public void setExempt(Integer exempt) {
        this.exempt = exempt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exemptions.comment
     *
     * @return the value of exemptions.comment
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exemptions.comment
     *
     * @param comment the value for exemptions.comment
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exemptions
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getName());
        sb.append("[");
        sb.append("Hash = ").append(hashCode());
        sb.append(",id=").append(id);
        sb.append(",personid=").append(personid);
        sb.append(",endterm=").append(endterm);
        sb.append(",exempt=").append(exempt);
        sb.append(",comment=").append(comment);
        sb.append(",serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exemptions
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    @Override
    public Object get(String name) {
        if (name.equals("id")) return id;
        if (name.equals("personid")) return personid;
        if (name.equals("endterm")) return endterm;
        if (name.equals("exempt")) return exempt;
        if (name.equals("comment")) return comment;
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exemptions
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    @Override
    public void set(String name, Object value) {
        if (name.equals("id")) id = value==null?null:(java.lang.Integer) value;
        if (name.equals("personid")) personid = value==null?null:(java.lang.Integer) value;
        if (name.equals("endterm")) endterm = value==null?null:(java.sql.Date) value;
        if (name.equals("exempt")) exempt = value==null?null:(java.lang.Integer) value;
        if (name.equals("comment")) comment = value==null?null:(java.lang.String) value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exemptions
     *
     * @mbggenerated Thu Aug 28 14:07:53 CDT 2014
     */
    @Override
    public void copy(Object a) {
        Exemptions castObject = (Exemptions) a;
        this.id = castObject.id;
        this.personid = castObject.personid;
        this.endterm = castObject.endterm;
        this.exempt = castObject.exempt;
        this.comment = castObject.comment;
    }

    public String simpleName() {
        return "Exemptions";
    }
}