package com.ritchey.simple.domain.chapel;

import java.util.ArrayList;
import java.util.List;

public class PropertiesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    public PropertiesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getName());
        sb.append("[");
        sb.append("Hash = ").append(hashCode());
        sb.append(",orderByClause=").append(orderByClause);
        sb.append(",distinct=").append(distinct);
        sb.append(",oredCriteria=").append(oredCriteria);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andKeyvalueIsNull() {
            addCriterion("keyValue is null");
            return (Criteria) this;
        }

        public Criteria andKeyvalueIsNotNull() {
            addCriterion("keyValue is not null");
            return (Criteria) this;
        }

        public Criteria andKeyvalueEqualTo(String value) {
            addCriterion("keyValue =", value, "keyvalue");
            return (Criteria) this;
        }

        public Criteria andKeyvalueNotEqualTo(String value) {
            addCriterion("keyValue <>", value, "keyvalue");
            return (Criteria) this;
        }

        public Criteria andKeyvalueGreaterThan(String value) {
            addCriterion("keyValue >", value, "keyvalue");
            return (Criteria) this;
        }

        public Criteria andKeyvalueGreaterThanOrEqualTo(String value) {
            addCriterion("keyValue >=", value, "keyvalue");
            return (Criteria) this;
        }

        public Criteria andKeyvalueLessThan(String value) {
            addCriterion("keyValue <", value, "keyvalue");
            return (Criteria) this;
        }

        public Criteria andKeyvalueLessThanOrEqualTo(String value) {
            addCriterion("keyValue <=", value, "keyvalue");
            return (Criteria) this;
        }

        public Criteria andKeyvalueLike(String value) {
            addCriterion("keyValue like", value, "keyvalue");
            return (Criteria) this;
        }

        public Criteria andKeyvalueNotLike(String value) {
            addCriterion("keyValue not like", value, "keyvalue");
            return (Criteria) this;
        }

        public Criteria andKeyvalueIn(List<String> values) {
            addCriterion("keyValue in", values, "keyvalue");
            return (Criteria) this;
        }

        public Criteria andKeyvalueNotIn(List<String> values) {
            addCriterion("keyValue not in", values, "keyvalue");
            return (Criteria) this;
        }

        public Criteria andKeyvalueBetween(String value1, String value2) {
            addCriterion("keyValue between", value1, value2, "keyvalue");
            return (Criteria) this;
        }

        public Criteria andKeyvalueNotBetween(String value1, String value2) {
            addCriterion("keyValue not between", value1, value2, "keyvalue");
            return (Criteria) this;
        }

        public Criteria andStrvalueIsNull() {
            addCriterion("strValue is null");
            return (Criteria) this;
        }

        public Criteria andStrvalueIsNotNull() {
            addCriterion("strValue is not null");
            return (Criteria) this;
        }

        public Criteria andStrvalueEqualTo(String value) {
            addCriterion("strValue =", value, "strvalue");
            return (Criteria) this;
        }

        public Criteria andStrvalueNotEqualTo(String value) {
            addCriterion("strValue <>", value, "strvalue");
            return (Criteria) this;
        }

        public Criteria andStrvalueGreaterThan(String value) {
            addCriterion("strValue >", value, "strvalue");
            return (Criteria) this;
        }

        public Criteria andStrvalueGreaterThanOrEqualTo(String value) {
            addCriterion("strValue >=", value, "strvalue");
            return (Criteria) this;
        }

        public Criteria andStrvalueLessThan(String value) {
            addCriterion("strValue <", value, "strvalue");
            return (Criteria) this;
        }

        public Criteria andStrvalueLessThanOrEqualTo(String value) {
            addCriterion("strValue <=", value, "strvalue");
            return (Criteria) this;
        }

        public Criteria andStrvalueLike(String value) {
            addCriterion("strValue like", value, "strvalue");
            return (Criteria) this;
        }

        public Criteria andStrvalueNotLike(String value) {
            addCriterion("strValue not like", value, "strvalue");
            return (Criteria) this;
        }

        public Criteria andStrvalueIn(List<String> values) {
            addCriterion("strValue in", values, "strvalue");
            return (Criteria) this;
        }

        public Criteria andStrvalueNotIn(List<String> values) {
            addCriterion("strValue not in", values, "strvalue");
            return (Criteria) this;
        }

        public Criteria andStrvalueBetween(String value1, String value2) {
            addCriterion("strValue between", value1, value2, "strvalue");
            return (Criteria) this;
        }

        public Criteria andStrvalueNotBetween(String value1, String value2) {
            addCriterion("strValue not between", value1, value2, "strvalue");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table properties
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 05 11:35:45 CDT 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}