package com.ritchey.simple.domain.chapel;

import java.io.Serializable;

public class Properties implements Reflect, Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column properties.id
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column properties.keyValue
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    private String keyvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column properties.strValue
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    private String strvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    private static final long serialVersionUID = 20130905113545L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column properties.id
     *
     * @return the value of properties.id
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column properties.id
     *
     * @param id the value for properties.id
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column properties.keyValue
     *
     * @return the value of properties.keyValue
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    public String getKeyvalue() {
        return keyvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column properties.keyValue
     *
     * @param keyvalue the value for properties.keyValue
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    public void setKeyvalue(String keyvalue) {
        this.keyvalue = keyvalue == null ? null : keyvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column properties.strValue
     *
     * @return the value of properties.strValue
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    public String getStrvalue() {
        return strvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column properties.strValue
     *
     * @param strvalue the value for properties.strValue
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    public void setStrvalue(String strvalue) {
        this.strvalue = strvalue == null ? null : strvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getName());
        sb.append("[");
        sb.append("Hash = ").append(hashCode());
        sb.append(",id=").append(id);
        sb.append(",keyvalue=").append(keyvalue);
        sb.append(",strvalue=").append(strvalue);
        sb.append(",serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    @Override
    public Object get(String name) {
        if (name.equals("id")) return id;
        if (name.equals("keyvalue")) return keyvalue;
        if (name.equals("strvalue")) return strvalue;
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    @Override
    public void set(String name, Object value) {
        if (name.equals("id")) id = value==null?null:(java.lang.Integer) value;
        if (name.equals("keyvalue")) keyvalue = value==null?null:(java.lang.String) value;
        if (name.equals("strvalue")) strvalue = value==null?null:(java.lang.String) value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbggenerated Thu Sep 05 11:35:45 CDT 2013
     */
    @Override
    public void copy(Object a) {
        Properties castObject = (Properties) a;
        this.id = castObject.id;
        this.keyvalue = castObject.keyvalue;
        this.strvalue = castObject.strvalue;
    }

    public String simpleName() {
        return "Properties";
    }
}