package com.ritchey.simple.domain.chapel;

import java.io.Serializable;
import java.util.Date;

public class Punch implements Reflect, Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punch.id
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punch.punchTime
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    private Date punchtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punch.campusId
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    private String campusid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punch.value
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    private Double value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punch.event
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    private Integer event;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punch.login
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    private String login;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punch.tardy
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    private Boolean tardy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punch.comment
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table punch
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    private static final long serialVersionUID = 20130904133312L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punch.id
     *
     * @return the value of punch.id
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punch.id
     *
     * @param id the value for punch.id
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punch.punchTime
     *
     * @return the value of punch.punchTime
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    public Date getPunchtime() {
        return punchtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punch.punchTime
     *
     * @param punchtime the value for punch.punchTime
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    public void setPunchtime(Date punchtime) {
        this.punchtime = punchtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punch.campusId
     *
     * @return the value of punch.campusId
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    public String getCampusid() {
        return campusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punch.campusId
     *
     * @param campusid the value for punch.campusId
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    public void setCampusid(String campusid) {
        this.campusid = campusid == null ? null : campusid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punch.value
     *
     * @return the value of punch.value
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    public Double getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punch.value
     *
     * @param value the value for punch.value
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    public void setValue(Double value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punch.event
     *
     * @return the value of punch.event
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    public Integer getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punch.event
     *
     * @param event the value for punch.event
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    public void setEvent(Integer event) {
        this.event = event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punch.login
     *
     * @return the value of punch.login
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    public String getLogin() {
        return login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punch.login
     *
     * @param login the value for punch.login
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    public void setLogin(String login) {
        this.login = login == null ? null : login.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punch.tardy
     *
     * @return the value of punch.tardy
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    public Boolean getTardy() {
        return tardy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punch.tardy
     *
     * @param tardy the value for punch.tardy
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    public void setTardy(Boolean tardy) {
        this.tardy = tardy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punch.comment
     *
     * @return the value of punch.comment
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punch.comment
     *
     * @param comment the value for punch.comment
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punch
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getName());
        sb.append("[");
        sb.append("Hash = ").append(hashCode());
        sb.append(",id=").append(id);
        sb.append(",punchtime=").append(punchtime);
        sb.append(",campusid=").append(campusid);
        sb.append(",value=").append(value);
        sb.append(",event=").append(event);
        sb.append(",login=").append(login);
        sb.append(",tardy=").append(tardy);
        sb.append(",comment=").append(comment);
        sb.append(",serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punch
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    @Override
    public Object get(String name) {
        if (name.equals("id")) return id;
        if (name.equals("punchtime")) return punchtime;
        if (name.equals("campusid")) return campusid;
        if (name.equals("value")) return value;
        if (name.equals("event")) return event;
        if (name.equals("login")) return login;
        if (name.equals("tardy")) return tardy;
        if (name.equals("comment")) return comment;
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punch
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    @Override
    public void set(String name, Object value) {
        if (name.equals("id")) id = value==null?null:(java.lang.Integer) value;
        if (name.equals("punchtime")) punchtime = value==null?null:(java.util.Date) value;
        if (name.equals("campusid")) campusid = value==null?null:(java.lang.String) value;
        if (name.equals("value")) value = value==null?null:(java.lang.Double) value;
        if (name.equals("event")) event = value==null?null:(java.lang.Integer) value;
        if (name.equals("login")) login = value==null?null:(java.lang.String) value;
        if (name.equals("tardy")) tardy = value==null?null:(java.lang.Boolean) value;
        if (name.equals("comment")) comment = value==null?null:(java.lang.String) value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punch
     *
     * @mbggenerated Wed Sep 04 13:33:12 CDT 2013
     */
    @Override
    public void copy(Object a) {
        Punch castObject = (Punch) a;
        this.id = castObject.id;
        this.punchtime = castObject.punchtime;
        this.campusid = castObject.campusid;
        this.value = castObject.value;
        this.event = castObject.event;
        this.login = castObject.login;
        this.tardy = castObject.tardy;
        this.comment = castObject.comment;
    }

    public String simpleName() {
        return "Punch";
    }
}